### ISSUE TITLE
Run debugging

### ISSUE THREAD

**Issue by krober10nd** [oceanmodeling/adcircpy#110]
* Given a log file and a crashed fort.63.nc, it could be useful to have `Fort63` produce an animation automatically finding the appropriate bbox. 
* This could be a simple function that calls `Fort63.animation` but additionally reads the log file, finds the node which first exhibited the instability then draws a small region around this area.

**Comment by jreniel** [comment]
Try the cmd line `fort63` with argument `--diagnose`. Pass the log life that contains the Elev.Gt.Than message as argument to `--diagnose`.

**Comment by krober10nd** [comment]
Ok thanks. I'll do this without the API since I'm working on some library scripts that use it.

**Comment by jreniel** [comment]
You could extend the [animation function](https://github.com/JaimeCalzadaVIMS/adcircpy/blob/main/adcircpy/cmd/fort63.py#L89-L100) to include the same `--diagnose` options as in the plot function.
But the main problem with this is that it depends too much on having the actual blowup on the fort.63 which most of the time doesn't happen. One thing that ADCIRC doesn't have (and should) is that it should always output the last timestep when the code aborts due to Elev.Gt... Other models, like FUNWAVE, do this by default.

**Comment by krober10nd** [comment]
Yea, however this option would be for the specific case of trying to diagnose a failed run...If there are no output warnings then it could simply tell just plot the fort.63.nc as is.

**Comment by krober10nd** [comment]
I'll do that.

**Comment by jreniel** [comment]
Since the blowup is almost never captured by fort.63, I normally just check with the `fort63 plot [...] --diagnose [...]` options to check at least _where_ it happened. Unless you have a high frequency surface output, your fort.63.nc will likely not show the actual blowup step.

**Comment by krober10nd** [comment]
Yes, I realize that.
