### ISSUE TITLE
CI testing system

### ISSUE THREAD

**Issue by krober10nd** [oceanmodeling/adcircpy#83]
* It appears unit tests are configured but do not run automatically. Is there a reason for this?
* Github actions seem to be the way to go for CI testing here.

**Comment by jreniel** [comment]
We have GitHub actions configured, see https://github.com/JaimeCalzadaNOAA/adcircpy/tree/main/.github/workflows.
They are running automagically, see https://github.com/JaimeCalzadaNOAA/adcircpy/runs/2585862921.
Could you elaborate why does it seem like this is not working correctly from your perspective?
Thanks!

**Comment by krober10nd** [comment]
ah okay sorry then, I guess I was expecting the PR to be CI tested but maybe you have to authorize that.

**Comment by jreniel** [comment]
Let's ask @zacharyburnettNOAA , but he's currently out on vacay, we'll have to wait.

**Comment by jreniel** [comment]
@krober10nd Our testing system is not perfect. Feel free to suggest new GitHub workflows and/or unittests that you feel might be useful or necessary.

**Comment by krober10nd** [comment]
Sure yea I can take a look tomorrow.

**Comment by krober10nd** [comment]
One suggestion would be to make the unit tests small README examples and then use this https://pypi.org/project/pytest-codeblocks/ to execute the README. 

If people don't see simple examples on a README, about 95% of them just give up unfortunately (maybe you don't want users like that anyway ;])

Anyway with pytest-codeblocks It's a win-win. You test your API, you present minimal working examples (that are guaranteed to work), and you unit test all at the same time.

For example, the least tested module (and also quite interesting one to me) is the OWI one. How does this module work? Could a short example be created for the README?

**Comment by ghost** [comment]
> One suggestion would be to make the unit tests small README examples and then use this https://pypi.org/project/pytest-codeblocks/ to execute the README.
> 
> If people don't see simple examples on a README, about 95% of them just give up unfortunately (maybe you don't want users like that anyway ;])
> 
> Anyway with pytest-codeblocks It's a win-win. You test your API, you present minimal working examples (that are guaranteed to work), and you unit test all at the same time.
> 
Those ideas are always welcome, the main problem with the unittests is that I don't have sufficient time in my hands to write these frameworks. We have the most critical parts covered through unittests and GitHub actions, but of course, more tests and working examples are always welcome. Part of the deal is that this software is not perfect and any person interested needs to understand that these are development codes, therefore, they are provided as-is to the end users. However, for developers it's a different story, because developers might be interested in filling-in gaps missing on the code. You are welcome to contribute these missing pieces.

> For example, the least tested module (and also quite interesting one to me) is the OWI one. How does this module work? Could a short example be created for the README?
>

The OWI module doesn't do anything useful at this stage. Right now all it has is a basic parser. The idea with having the parser is that we have documented the data structure, without having to have actual data, since this is proprietary data. But the bottom line is we never really used this, but it could be used to tell the AdcircDriver object that the user wants to use some OWI winds, so make sure to populate the fort.15 accordingly. However, like I mentioned, that module has hardly been used in practice so it's an unfinished code. Of course, being object-oriented, the possibilities are endless. You could use these classes to read sequentially the OWI files and plot them, create movies, modify them, etc... The limits are your imagination and how much effort you are willing to put to it.

**Comment by krober10nd** [comment]
Gotcha. So then the code coverage is skewed down if there's unfinished code in main. Well, then let's add the tests as we add new features. 

I often need to produce high quality plots in a standard way and will probably work on this on a need-to-need basis. This will likely be my next use case.
