### ISSUE TITLE
Linter bot failing for unknown reason.

### ISSUE THREAD

**Issue by jreniel** [oceanmodeling/adcircpy#97]
https://github.com/JaimeCalzadaNOAA/adcircpy/runs/2693802968?check_suite_focus=true

**Comment by ghost** [comment]
last time this happened it was because `isort` was changing the files before the linter started, so when it did `git commit` it had unexpected changes. I thought I had fixed this problem by using the `oitnb_prefix_command` but apparently not. I will take out the `isort` call for now to see if that fixes the problem
